variables:
  SolutionBaseName: 'DFC.App.Lmi.Delta.Report'
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'
  ArmTemplateRoot: '$(Build.SourcesDirectory)\Resources\ArmTemplates'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.11.2
    endpoint: 'GitHub (ESFA)'

pool:
  name: NCS - CI and CD
  demands:
  - msbuild
  - visualstudio

trigger: 
  branches:
    include: 
    - dev
    - master

pr:
  branches:
    include: 
    - dev
    - master

stages:
- stage: Build
  jobs:
  - job:
    displayName: Build and test application & templates"
    steps:

    - template: /AzureDevOpsTemplates/Build/StepTemplates/dfc-arm-build.yml@dfc-devops
      parameters:
        ArmTemplateRoot: '${{ variables.ArmTemplateRoot }}'
        SolutionBaseName: '${{ variables.SolutionBaseName }}'

    - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcore-build-sonar.yml@dfc-devops
      parameters:
        SolutionBaseName: $(SolutionBaseName)
        BuildPlatform: $(BuildPlatform)
        BuildConfiguration: $(BuildConfiguration)
        DotNetCoreVersion: '3.1.100'
        PublishWebApp: true
        TestSuffix: UnitTests

- stage: DeployToDev
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
  displayName: Deploy to Dev
  variables:
  - group: dfc-shared-all
  - group: dfc-shared-dev
  - group: dfc-app-shared-all
  - group: dfc-app-shared-dev
  - template: VariableTemplates\DevEnvironmentVariables.yml

  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: $(ResourceGroup)
      DfCDevopsPath: '$(Agent.BuildDirectory)/s/dfc-devops'
      PackageFile:  "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.DeploymentPackages/${{ variables.SolutionBaseName }}.zip"
      ArmTemplateFolder: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ArmTemplates/"
      EnvironmentName: Dev_AppLmiDeltaReport
      AppSharedResourceGroup: $(AppSharedResourceGroup)
      AppServiceName: '$(AppServiceName)'

- stage: DeployToSit
  condition: succeeded()
  displayName: Deploy to Sit
  variables:
  - group: dfc-shared-all
  - group: dfc-shared-sit
  - group: dfc-app-shared-all
  - group: dfc-app-shared-sit
  - template: VariableTemplates\SitEnvironmentVariables.yml

  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: $(ResourceGroup)
      DfCDevopsPath: '$(Agent.BuildDirectory)/s/dfc-devops'
      PackageFile:  "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.DeploymentPackages/${{ variables.SolutionBaseName }}.zip"
      ArmTemplateFolder: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ArmTemplates/"
      EnvironmentName: Sit_AppLmiDeltaReport
      AppSharedResourceGroup: $(AppSharedResourceGroup)
      AppServiceName: '$(AppServiceName)'

- stage: DeployToPP
  condition: and(eq(dependencies.Build.result,'Succeeded'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: Deploy to PP
  variables:
  - group: dfc-shared-all
  - group: dfc-shared-pp
  - group: dfc-app-shared-all
  - group: dfc-app-shared-pp
  - template: VariableTemplates\PPEnvironmentVariables.yml

  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-DIG-PreProd (931bc9f6-359c-4f65-a753-1ee191a1fd6c)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: $(ResourceGroup)
      DfCDevopsPath: '$(Agent.BuildDirectory)/s/dfc-devops'
      PackageFile:  "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.DeploymentPackages/${{ variables.SolutionBaseName }}.zip"
      ArmTemplateFolder: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ArmTemplates/"
      EnvironmentName: PP_AppLmiDeltaReport
      AppSharedResourceGroup: $(AppSharedResourceGroup)
      AppServiceName: '$(AppServiceName)'

- stage: DeployToPrd
  condition: and(eq(dependencies.DeployToPP.result,'Succeeded'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: Deploy to Prd
  variables:
  - group: dfc-shared-all
  - group: dfc-shared-prd
  - group: dfc-app-shared-all
  - group: dfc-app-shared-prd
  - template: VariableTemplates\PrdEnvironmentVariables.yml

  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-DIG-Prod (6c93f7dc-6c36-4ea6-8de3-3f4574f88027)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: $(ResourceGroup)
      DfCDevopsPath: '$(Agent.BuildDirectory)/s/dfc-devops'
      PackageFile:  "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.DeploymentPackages/${{ variables.SolutionBaseName }}.zip"
      ArmTemplateFolder: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ArmTemplates/"
      EnvironmentName: Prd_AppLmiDeltaReport
      AppSharedResourceGroup: $(AppSharedResourceGroup)
      AppServiceName: '$(AppServiceName)'